export const TOLERANCE_COLOR_STYLES = {
  // Existing custom palette
  'neon-blue': {
    id: 'neon-blue',
    label: 'Neon Blue',
    swatch: 'bg-neon-blue',
    text: 'text-neon-blue',
    bgTemp: 'bg-neon-blue/25',
    bgHum: 'bg-neon-blue/20',
    bgLuxStrong: 'bg-neon-blue/30',
    ring30: 'ring-neon-blue/30',
    ring40: 'ring-neon-blue/40',
  },
  'neon-green': {
    id: 'neon-green',
    label: 'Neon Green',
    swatch: 'bg-neon-green',
    text: 'text-neon-green',
    bgTemp: 'bg-neon-green/25',
    bgHum: 'bg-neon-green/20',
    bgLuxStrong: 'bg-neon-green/30',
    ring30: 'ring-neon-green/30',
    ring40: 'ring-neon-green/40',
  },
  warning: {
    id: 'warning',
    label: 'Amber',
    swatch: 'bg-warning',
    text: 'text-warning',
    bgTemp: 'bg-warning/15',
    bgHum: 'bg-warning/12',
    bgLuxStrong: 'bg-warning/18',
    ring30: 'ring-warning/30',
    ring40: 'ring-warning/40',
  },
  'neon-red': {
    id: 'neon-red',
    label: 'Neon Red',
    swatch: 'bg-neon-red',
    text: 'text-neon-red',
    bgTemp: 'bg-neon-red/25',
    bgHum: 'bg-neon-red/20',
    bgLuxStrong: 'bg-neon-red/30',
    ring30: 'ring-neon-red/30',
    ring40: 'ring-neon-red/40',
  },
  primary: {
    id: 'primary',
    label: 'Primary Blue',
    swatch: 'bg-primary',
    text: 'text-primary',
    bgTemp: 'bg-primary/25',
    bgHum: 'bg-primary/20',
    bgLuxStrong: 'bg-primary/30',
    ring30: 'ring-primary/30',
    ring40: 'ring-primary/40',
  },
  success: {
    id: 'success',
    label: 'Success Green',
    swatch: 'bg-success',
    text: 'text-success',
    bgTemp: 'bg-success/25',
    bgHum: 'bg-success/20',
    bgLuxStrong: 'bg-success/30',
    ring30: 'ring-success/30',
    ring40: 'ring-success/40',
  },
  danger: {
    id: 'danger',
    label: 'Danger Red',
    swatch: 'bg-danger',
    text: 'text-danger',
    bgTemp: 'bg-danger/25',
    bgHum: 'bg-danger/20',
    bgLuxStrong: 'bg-danger/30',
    ring30: 'ring-danger/30',
    ring40: 'ring-danger/40',
  },

  // Tailwind default palette (no custom hexes; gives a much wider choice)
  sky: {
    id: 'sky',
    label: 'Sky',
    swatch: 'bg-sky-400',
    text: 'text-sky-400',
    bgTemp: 'bg-sky-400/25',
    bgHum: 'bg-sky-400/20',
    bgLuxStrong: 'bg-sky-400/30',
    ring30: 'ring-sky-400/30',
    ring40: 'ring-sky-400/40',
  },
  cyan: {
    id: 'cyan',
    label: 'Cyan',
    swatch: 'bg-cyan-400',
    text: 'text-cyan-400',
    bgTemp: 'bg-cyan-400/25',
    bgHum: 'bg-cyan-400/20',
    bgLuxStrong: 'bg-cyan-400/30',
    ring30: 'ring-cyan-400/30',
    ring40: 'ring-cyan-400/40',
  },
  teal: {
    id: 'teal',
    label: 'Teal',
    swatch: 'bg-teal-400',
    text: 'text-teal-400',
    bgTemp: 'bg-teal-400/25',
    bgHum: 'bg-teal-400/20',
    bgLuxStrong: 'bg-teal-400/30',
    ring30: 'ring-teal-400/30',
    ring40: 'ring-teal-400/40',
  },
  emerald: {
    id: 'emerald',
    label: 'Emerald',
    swatch: 'bg-emerald-400',
    text: 'text-emerald-400',
    bgTemp: 'bg-emerald-400/25',
    bgHum: 'bg-emerald-400/20',
    bgLuxStrong: 'bg-emerald-400/30',
    ring30: 'ring-emerald-400/30',
    ring40: 'ring-emerald-400/40',
  },
  lime: {
    id: 'lime',
    label: 'Lime',
    swatch: 'bg-lime-400',
    text: 'text-lime-400',
    bgTemp: 'bg-lime-400/25',
    bgHum: 'bg-lime-400/20',
    bgLuxStrong: 'bg-lime-400/30',
    ring30: 'ring-lime-400/30',
    ring40: 'ring-lime-400/40',
  },
  yellow: {
    id: 'yellow',
    label: 'Yellow',
    swatch: 'bg-yellow-400',
    text: 'text-yellow-400',
    bgTemp: 'bg-yellow-400/20',
    bgHum: 'bg-yellow-400/16',
    bgLuxStrong: 'bg-yellow-400/26',
    ring30: 'ring-yellow-400/30',
    ring40: 'ring-yellow-400/40',
  },
  orange: {
    id: 'orange',
    label: 'Orange',
    swatch: 'bg-orange-400',
    text: 'text-orange-400',
    bgTemp: 'bg-orange-400/25',
    bgHum: 'bg-orange-400/20',
    bgLuxStrong: 'bg-orange-400/30',
    ring30: 'ring-orange-400/30',
    ring40: 'ring-orange-400/40',
  },
  rose: {
    id: 'rose',
    label: 'Rose',
    swatch: 'bg-rose-400',
    text: 'text-rose-400',
    bgTemp: 'bg-rose-400/25',
    bgHum: 'bg-rose-400/20',
    bgLuxStrong: 'bg-rose-400/30',
    ring30: 'ring-rose-400/30',
    ring40: 'ring-rose-400/40',
  },
  pink: {
    id: 'pink',
    label: 'Pink',
    swatch: 'bg-pink-400',
    text: 'text-pink-400',
    bgTemp: 'bg-pink-400/25',
    bgHum: 'bg-pink-400/20',
    bgLuxStrong: 'bg-pink-400/30',
    ring30: 'ring-pink-400/30',
    ring40: 'ring-pink-400/40',
  },
  fuchsia: {
    id: 'fuchsia',
    label: 'Fuchsia',
    swatch: 'bg-fuchsia-400',
    text: 'text-fuchsia-400',
    bgTemp: 'bg-fuchsia-400/25',
    bgHum: 'bg-fuchsia-400/20',
    bgLuxStrong: 'bg-fuchsia-400/30',
    ring30: 'ring-fuchsia-400/30',
    ring40: 'ring-fuchsia-400/40',
  },
  purple: {
    id: 'purple',
    label: 'Purple',
    swatch: 'bg-purple-400',
    text: 'text-purple-400',
    bgTemp: 'bg-purple-400/25',
    bgHum: 'bg-purple-400/20',
    bgLuxStrong: 'bg-purple-400/30',
    ring30: 'ring-purple-400/30',
    ring40: 'ring-purple-400/40',
  },
  violet: {
    id: 'violet',
    label: 'Violet',
    swatch: 'bg-violet-400',
    text: 'text-violet-400',
    bgTemp: 'bg-violet-400/25',
    bgHum: 'bg-violet-400/20',
    bgLuxStrong: 'bg-violet-400/30',
    ring30: 'ring-violet-400/30',
    ring40: 'ring-violet-400/40',
  },
  indigo: {
    id: 'indigo',
    label: 'Indigo',
    swatch: 'bg-indigo-400',
    text: 'text-indigo-400',
    bgTemp: 'bg-indigo-400/25',
    bgHum: 'bg-indigo-400/20',
    bgLuxStrong: 'bg-indigo-400/30',
    ring30: 'ring-indigo-400/30',
    ring40: 'ring-indigo-400/40',
  },
  blue: {
    id: 'blue',
    label: 'Blue',
    swatch: 'bg-blue-400',
    text: 'text-blue-400',
    bgTemp: 'bg-blue-400/25',
    bgHum: 'bg-blue-400/20',
    bgLuxStrong: 'bg-blue-400/30',
    ring30: 'ring-blue-400/30',
    ring40: 'ring-blue-400/40',
  },
  slate: {
    id: 'slate',
    label: 'Slate',
    swatch: 'bg-slate-500',
    text: 'text-slate-400',
    bgTemp: 'bg-slate-500/20',
    bgHum: 'bg-slate-500/16',
    bgLuxStrong: 'bg-slate-500/24',
    ring30: 'ring-slate-500/30',
    ring40: 'ring-slate-500/40',
  },

  // More natural palette options
  amber: {
    id: 'amber',
    label: 'Amber (Sand)',
    swatch: 'bg-amber-400',
    text: 'text-amber-400',
    bgTemp: 'bg-amber-400/22',
    bgHum: 'bg-amber-400/16',
    bgLuxStrong: 'bg-amber-400/26',
    ring30: 'ring-amber-400/30',
    ring40: 'ring-amber-400/40',
  },
  stone: {
    id: 'stone',
    label: 'Stone',
    swatch: 'bg-stone-400',
    text: 'text-stone-300',
    bgTemp: 'bg-stone-400/20',
    bgHum: 'bg-stone-400/16',
    bgLuxStrong: 'bg-stone-400/24',
    ring30: 'ring-stone-400/30',
    ring40: 'ring-stone-400/40',
  },

  // Neutral/base colors (for "colorize only the hot stuff" workflows)
  white: {
    id: 'white',
    label: 'White',
    swatch: 'bg-white',
    text: 'text-white',
    bgTemp: 'bg-white/10',
    bgHum: 'bg-white/8',
    bgLuxStrong: 'bg-white/12',
    ring30: 'ring-white/30',
    ring40: 'ring-white/40',
  },
  black: {
    id: 'black',
    label: 'Black',
    swatch: 'bg-black',
    text: 'text-black',
    bgTemp: 'bg-black/20',
    bgHum: 'bg-black/16',
    bgLuxStrong: 'bg-black/24',
    ring30: 'ring-black/30',
    ring40: 'ring-black/40',
  },
  zinc: {
    id: 'zinc',
    label: 'Zinc',
    swatch: 'bg-zinc-400',
    text: 'text-zinc-300',
    bgTemp: 'bg-zinc-400/20',
    bgHum: 'bg-zinc-400/16',
    bgLuxStrong: 'bg-zinc-400/24',
    ring30: 'ring-zinc-400/30',
    ring40: 'ring-zinc-400/40',
  },
  neutral: {
    id: 'neutral',
    label: 'Neutral',
    swatch: 'bg-neutral-400',
    text: 'text-neutral-300',
    bgTemp: 'bg-neutral-400/20',
    bgHum: 'bg-neutral-400/16',
    bgLuxStrong: 'bg-neutral-400/24',
    ring30: 'ring-neutral-400/30',
    ring40: 'ring-neutral-400/40',
  },
  tan: {
    id: 'tan',
    label: 'Tan',
    swatch: 'bg-amber-300',
    text: 'text-amber-300',
    bgTemp: 'bg-amber-300/18',
    bgHum: 'bg-amber-300/14',
    bgLuxStrong: 'bg-amber-300/22',
    ring30: 'ring-amber-300/30',
    ring40: 'ring-amber-300/40',
  },
  brown: {
    id: 'brown',
    label: 'Brown',
    swatch: 'bg-amber-700',
    text: 'text-amber-500',
    bgTemp: 'bg-amber-700/20',
    bgHum: 'bg-amber-700/16',
    bgLuxStrong: 'bg-amber-700/24',
    ring30: 'ring-amber-700/30',
    ring40: 'ring-amber-700/40',
  },
};

export const TOLERANCE_COLOR_CHOICES = Object.values(TOLERANCE_COLOR_STYLES);

export const ALLOWED_TOLERANCE_COLOR_IDS = new Set(Object.keys(TOLERANCE_COLOR_STYLES));

export function normalizeToleranceColorId(value, fallback) {
  const s = String(value || '').trim();
  const fb = String(fallback || '').trim();
  if (ALLOWED_TOLERANCE_COLOR_IDS.has(s)) return s;
  if (ALLOWED_TOLERANCE_COLOR_IDS.has(fb)) return fb;
  return 'neon-green';
}

export function getToleranceColorStyle(colorId) {
  const id = normalizeToleranceColorId(colorId, 'neon-green');
  return TOLERANCE_COLOR_STYLES[id] || TOLERANCE_COLOR_STYLES['neon-green'];
}

export function getToleranceTextClass(colorId) {
  return getToleranceColorStyle(colorId).text;
}
