export const UI_COLOR_SCHEMES = {
  'electric-blue': {
    id: 'electric-blue',
    label: 'Electric Blue',
    swatch: 'bg-neon-blue',
    tabActive: 'bg-neon-blue/10 text-neon-blue',
    headerIcon: 'bg-neon-blue/20 border-neon-blue/50 text-neon-blue',
    headerGlow: 'animate-glow-blue',
    actionButton: 'text-neon-blue border-neon-blue/30 bg-neon-blue/10',
    checkboxAccent: 'accent-neon-blue',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-neon-blue/35 focus:border-neon-blue/40',
    selectedCard: 'border-neon-blue/40 bg-neon-blue/10',
    selectedText: 'text-neon-blue',
    metricIcon: 'text-neon-blue',
    editBorder: 'border-neon-blue/30',
    editRing: 'ring-neon-blue/20',
    rgb: '0 212 255',
  },
  'classic-blue': {
    id: 'classic-blue',
    label: 'Classic Blue',
    swatch: 'bg-primary',
    tabActive: 'bg-primary/10 text-primary',
    headerIcon: 'bg-primary/20 border-primary/50 text-primary',
    headerGlow: 'animate-glow-blue',
    actionButton: 'text-primary border-primary/30 bg-primary/10',
    checkboxAccent: 'accent-primary',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-primary/35 focus:border-primary/40',
    selectedCard: 'border-primary/40 bg-primary/10',
    selectedText: 'text-primary',
    metricIcon: 'text-primary',
    editBorder: 'border-primary/30',
    editRing: 'ring-primary/20',
    rgb: '59 130 246',
  },
  emerald: {
    id: 'emerald',
    label: 'Emerald',
    swatch: 'bg-success',
    tabActive: 'bg-success/10 text-success',
    headerIcon: 'bg-success/20 border-success/50 text-success',
    headerGlow: '',
    actionButton: 'text-success border-success/30 bg-success/10',
    checkboxAccent: 'accent-success',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-success/35 focus:border-success/40',
    selectedCard: 'border-success/40 bg-success/10',
    selectedText: 'text-success',
    metricIcon: 'text-success',
    editBorder: 'border-success/30',
    editRing: 'ring-success/20',
    rgb: '16 185 129',
  },
  amber: {
    id: 'amber',
    label: 'Amber',
    swatch: 'bg-warning',
    tabActive: 'bg-warning/10 text-warning',
    headerIcon: 'bg-warning/20 border-warning/50 text-warning',
    headerGlow: 'animate-glow-orange',
    actionButton: 'text-warning border-warning/30 bg-warning/10',
    checkboxAccent: 'accent-warning',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-warning/35 focus:border-warning/40',
    selectedCard: 'border-warning/40 bg-warning/10',
    selectedText: 'text-warning',
    metricIcon: 'text-warning',
    editBorder: 'border-warning/30',
    editRing: 'ring-warning/20',
    rgb: '245 158 11',
  },
  'neon-green': {
    id: 'neon-green',
    label: 'Neon Green',
    swatch: 'bg-neon-green',
    tabActive: 'bg-neon-green/10 text-neon-green',
    headerIcon: 'bg-neon-green/20 border-neon-green/50 text-neon-green',
    headerGlow: '',
    actionButton: 'text-neon-green border-neon-green/30 bg-neon-green/10',
    checkboxAccent: 'accent-neon-green',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-neon-green/35 focus:border-neon-green/40',
    selectedCard: 'border-neon-green/40 bg-neon-green/10',
    selectedText: 'text-neon-green',
    metricIcon: 'text-neon-green',
    editBorder: 'border-neon-green/30',
    editRing: 'ring-neon-green/20',
    rgb: '0 255 157',
  },
  'neon-red': {
    id: 'neon-red',
    label: 'Neon Red',
    swatch: 'bg-neon-red',
    tabActive: 'bg-neon-red/10 text-neon-red',
    headerIcon: 'bg-neon-red/20 border-neon-red/50 text-neon-red',
    headerGlow: 'animate-glow-red',
    actionButton: 'text-neon-red border-neon-red/30 bg-neon-red/10',
    checkboxAccent: 'accent-neon-red',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-neon-red/35 focus:border-neon-red/40',
    selectedCard: 'border-neon-red/40 bg-neon-red/10',
    selectedText: 'text-neon-red',
    metricIcon: 'text-neon-red',
    editBorder: 'border-neon-red/30',
    editRing: 'ring-neon-red/20',
    rgb: '255 0 85',
  },
};

export function getUiScheme(colorSchemeId) {
  const key = String(colorSchemeId || '').trim();
  return UI_COLOR_SCHEMES[key] || UI_COLOR_SCHEMES['electric-blue'];
}
