export const UI_COLOR_SCHEMES = {
  'electric-blue': {
    id: 'electric-blue',
    label: 'Electric Blue',
    swatch: 'bg-neon-blue',
    tabActive: 'bg-neon-blue/10 text-neon-blue',
    headerIcon: 'bg-neon-blue/20 border-neon-blue/50 text-neon-blue',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-neon-blue border-neon-blue/30 bg-neon-blue/10',
    checkboxAccent: 'accent-neon-blue',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-neon-blue/35 focus:border-neon-blue/40',
    selectedCard: 'border-neon-blue/40 bg-neon-blue/10',
    selectedText: 'text-neon-blue',
    metricIcon: 'text-neon-blue',
    editBorder: 'border-neon-blue/30',
    editRing: 'ring-neon-blue/20',
    rgb: '0 212 255',
  },
  'classic-blue': {
    id: 'classic-blue',
    label: 'Classic Blue',
    swatch: 'bg-primary',
    tabActive: 'bg-primary/10 text-primary',
    headerIcon: 'bg-primary/20 border-primary/50 text-primary',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-primary border-primary/30 bg-primary/10',
    checkboxAccent: 'accent-primary',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-primary/35 focus:border-primary/40',
    selectedCard: 'border-primary/40 bg-primary/10',
    selectedText: 'text-primary',
    metricIcon: 'text-primary',
    editBorder: 'border-primary/30',
    editRing: 'ring-primary/20',
    rgb: '59 130 246',
  },
  emerald: {
    id: 'emerald',
    label: 'Emerald',
    swatch: 'bg-success',
    tabActive: 'bg-success/10 text-success',
    headerIcon: 'bg-success/20 border-success/50 text-success',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-success border-success/30 bg-success/10',
    checkboxAccent: 'accent-success',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-success/35 focus:border-success/40',
    selectedCard: 'border-success/40 bg-success/10',
    selectedText: 'text-success',
    metricIcon: 'text-success',
    editBorder: 'border-success/30',
    editRing: 'ring-success/20',
    rgb: '16 185 129',
  },
  amber: {
    id: 'amber',
    label: 'Amber',
    swatch: 'bg-warning',
    tabActive: 'bg-warning/10 text-warning',
    headerIcon: 'bg-warning/20 border-warning/50 text-warning',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-warning border-warning/30 bg-warning/10',
    checkboxAccent: 'accent-warning',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-warning/35 focus:border-warning/40',
    selectedCard: 'border-warning/40 bg-warning/10',
    selectedText: 'text-warning',
    metricIcon: 'text-warning',
    editBorder: 'border-warning/30',
    editRing: 'ring-warning/20',
    rgb: '245 158 11',
  },
  'neon-green': {
    id: 'neon-green',
    label: 'Neon Green',
    swatch: 'bg-neon-green',
    tabActive: 'bg-neon-green/10 text-neon-green',
    headerIcon: 'bg-neon-green/20 border-neon-green/50 text-neon-green',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-neon-green border-neon-green/30 bg-neon-green/10',
    checkboxAccent: 'accent-neon-green',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-neon-green/35 focus:border-neon-green/40',
    selectedCard: 'border-neon-green/40 bg-neon-green/10',
    selectedText: 'text-neon-green',
    metricIcon: 'text-neon-green',
    editBorder: 'border-neon-green/30',
    editRing: 'ring-neon-green/20',
    rgb: '0 255 157',
  },
  'neon-red': {
    id: 'neon-red',
    label: 'Neon Red',
    swatch: 'bg-neon-red',
    tabActive: 'bg-neon-red/10 text-neon-red',
    headerIcon: 'bg-neon-red/20 border-neon-red/50 text-neon-red',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-neon-red border-neon-red/30 bg-neon-red/10',
    checkboxAccent: 'accent-neon-red',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-neon-red/35 focus:border-neon-red/40',
    selectedCard: 'border-neon-red/40 bg-neon-red/10',
    selectedText: 'text-neon-red',
    metricIcon: 'text-neon-red',
    editBorder: 'border-neon-red/30',
    editRing: 'ring-neon-red/20',
    rgb: '255 0 85',
  },

  // Neutral / base schemes
  slate: {
    id: 'slate',
    label: 'Slate (Charcoal)',
    swatch: 'bg-slate-500',
    tabActive: 'bg-slate-500/15 text-slate-200',
    headerIcon: 'bg-slate-500/20 border-slate-500/50 text-slate-200',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-slate-200 border-slate-500/35 bg-slate-500/15',
    checkboxAccent: 'accent-slate-400',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-slate-400/35 focus:border-slate-400/40',
    selectedCard: 'border-slate-500/45 bg-slate-500/10',
    selectedText: 'text-slate-200',
    metricIcon: 'text-slate-200',
    editBorder: 'border-slate-500/30',
    editRing: 'ring-slate-500/20',
    rgb: '148 163 184',
  },
  stone: {
    id: 'stone',
    label: 'Stone (Tan)',
    swatch: 'bg-stone-400',
    tabActive: 'bg-stone-400/15 text-stone-200',
    headerIcon: 'bg-stone-400/20 border-stone-400/50 text-stone-200',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-stone-200 border-stone-400/35 bg-stone-400/15',
    checkboxAccent: 'accent-stone-400',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-stone-400/35 focus:border-stone-400/40',
    selectedCard: 'border-stone-400/45 bg-stone-400/10',
    selectedText: 'text-stone-200',
    metricIcon: 'text-stone-200',
    editBorder: 'border-stone-400/30',
    editRing: 'ring-stone-400/20',
    rgb: '168 162 158',
  },
  zinc: {
    id: 'zinc',
    label: 'Zinc',
    swatch: 'bg-zinc-400',
    tabActive: 'bg-zinc-400/15 text-zinc-200',
    headerIcon: 'bg-zinc-400/20 border-zinc-400/50 text-zinc-200',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-zinc-200 border-zinc-400/35 bg-zinc-400/15',
    checkboxAccent: 'accent-zinc-400',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-zinc-400/35 focus:border-zinc-400/40',
    selectedCard: 'border-zinc-400/45 bg-zinc-400/10',
    selectedText: 'text-zinc-200',
    metricIcon: 'text-zinc-200',
    editBorder: 'border-zinc-400/30',
    editRing: 'ring-zinc-400/20',
    rgb: '161 161 170',
  },
  white: {
    id: 'white',
    label: 'White',
    swatch: 'bg-white',
    tabActive: 'bg-white/10 text-white',
    headerIcon: 'bg-white/10 border-white/30 text-white',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-white border-white/25 bg-white/10',
    checkboxAccent: 'accent-white',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-white/35 focus:border-white/40',
    selectedCard: 'border-white/35 bg-white/10',
    selectedText: 'text-white',
    metricIcon: 'text-white',
    editBorder: 'border-white/25',
    editRing: 'ring-white/20',
    rgb: '255 255 255',
  },
  copper: {
    id: 'copper',
    label: 'Copper (Brown)',
    swatch: 'bg-amber-700',
    tabActive: 'bg-amber-700/20 text-amber-300',
    headerIcon: 'bg-amber-700/20 border-amber-700/45 text-amber-300',
    headerGlow: 'animate-glow-accent',
    actionButton: 'text-amber-300 border-amber-700/40 bg-amber-700/20',
    checkboxAccent: 'accent-amber-500',
    focusRing: 'focus:outline-none focus:ring-2 focus:ring-amber-400/35 focus:border-amber-400/40',
    selectedCard: 'border-amber-700/45 bg-amber-700/15',
    selectedText: 'text-amber-300',
    metricIcon: 'text-amber-300',
    editBorder: 'border-amber-700/35',
    editRing: 'ring-amber-700/20',
    rgb: '245 158 11',
  },
};

export function getUiScheme(colorSchemeId) {
  const key = String(colorSchemeId || '').trim();
  return UI_COLOR_SCHEMES[key] || UI_COLOR_SCHEMES['electric-blue'];
}
